### ISSUE TITLE
Doesn't work on macOS 10.12

### ISSUE THREAD

**Issue by rodionovd** [rodionovd/shortcuts#5]
That's it:

```
  "_OBJC_CLASS_$_IMKTextReplacementController", referenced from:
      objc-class-ref in shortcuts.o
  "_OBJC_CLASS_$_IMKTextReplacementEntry", referenced from:
      objc-class-ref in shortcuts.o
  "_OBJC_CLASS_$_IMKTextReplacementEntryTransaction", referenced from:
      objc-class-ref in shortcuts.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by rodionovd** [comment]
So: 10.12 finally gets rid of InputMethodKit.framework in favour of a brand new KeyboardServices.framework. It means that 2.0.0 release will be Sierra-only.

**Comment by rodionovd** [comment]
Fixed in HEAD.
